files: chloris_app_sdk/\.+?\.py$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.0.1"
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      #   - id: detect-aws-credentials
      - id: detect-private-key
      - id: check-toml

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.263"
    hooks:
      - id: ruff
        exclude: ^(docker/)

  - repo: https://github.com/psf/black
    rev: "22.3.0"
    hooks:
      - id: black
        args: ["--line-length=120"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.2.0"
    hooks:
      - id: mypy
        args:
          [
            --no-strict-optional,
            --ignore-missing-imports,
            --disallow-untyped-defs,
            --disallow-incomplete-defs,
          ]
        exclude: ^(tests/|docker/)

  - repo: https://github.com/econchick/interrogate
    rev: "1.5.0"
    hooks:
      - id: interrogate
        args: [-vv, -i, -I]
        exclude: ^(tests/|docker/)
